version: '3'
services:
  web:
    restart: unless-stopped
    image: ultimatum_web
    build: .
    command: 
      "gunicorn --log-file /code/out.log --log-level debug --error-logfile=- --workers 1 survey.app:app --bind $GUNICORN_BIND --timeout 300"
    env_file: 
      - .env
    volumes:
      - .:/code
    working_dir: /code
  
  web_socket:
    image: ultimatum_web
    command: 
      "gunicorn --log-file /code/out.log --log-level debug --error-logfile=- --workers 1 survey.app:app --bind 0.0.0.0:5000 --timeout 300"
    environment: 
      - GUNICORN_BIND=0.0.0.0:5000
    ports:
      - "${HOST_WEB_PORT:-5000}:5000"
    volumes:
      - .:/code
    working_dir: /code
  

  test:
    image: ultimatum_web
    command: pytest tests/ -x
    environment: 
      - TXX=true
  
  notebook:
    ports:
      - "8888:8888"
    image: ultimatum_web
    volumes:
      - .:/code
    command: jupyter notebook --allow-root --ip=0.0.0.0 --port=8888
  